name: Build Browser Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Build Chrome ZIP
        run: npm run zip

      - name: Build Firefox thinggy idk :3
        run: npm run pack:zip
